name: Docker Image CI

on:
  push:
    branches: 
     - main
     
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . 
    - name: Docker tag
      run: docker tag my-image:v1 saikumaar/my-image:v1

    - name: docker push
      run: docker push saikumaar/my-inage:v1
